### ISSUE TITLE
[Suggestion] Hotkey to toggle Fullbright

### ISSUE THREAD

**Issue by JamesBach93** [BurgerbudeORG/labymod4-fullbright#2]
Hey, 

can you add an Hotkey to toggle the Fullbright.
I used it only for Support or Server side tasks. 
So everytime to open the Options and deactivate it is sometimes very anoying :D

**Comment by R0bbyYT** [comment]
Hey, this feature was added in version 1.1.8, you can now assign a hotkey in the settings.
